### ISSUE TITLE
[createWebSiteS3Bucket] The bucket you tried to delete is not empty

### ISSUE THREAD

**Issue by rezabekf** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#14] opened 2020-07-24 11:32 UTC
Stack fails to delete due to a S3 bucket not being empty.

Replication:
Delete deployed stack.

Proposed resolution:
Consider adding code below to the `createWebSiteS3Bucket` resource:
```
createWebSiteS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    {...}
```

**Comment by kqia040** [comment] 2020-08-30 22:42
Thanks, I'll close this issue as its a duplicate of https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/issues/15

**Closed as completed by kqia040** 2020-08-30 22:42 UTC
