### ISSUE TITLE
How to get the real time Transcript of both the agent as well as customer?

### ISSUE THREAD

**Issue by Sarthak-Kulkarni** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#22] opened 2021-04-06 07:15 UTC
The solution currently provides the real time transcript of the customer only. How will I be able to get the real-time transcript of what the agent is saying? @aman-appcino @efh365

**Comment by dfw100** [comment] 2021-04-19 19:52
I am closing this issue as duplicate of #24

**Closed as completed by dfw100** 2021-04-19 19:52 UTC
